version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=suivchantier
      - POSTGRES_USER=suivchantier_user
      - POSTGRES_PASSWORD=suivchantier_pass
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgres://suivchantier_user:suivchantier_pass@db:5432/suivchantier
    depends_on:
      - db

volumes:
  postgres_data:
